// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audiostream.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_audiostream_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_audiostream_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_audiostream_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_audiostream_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_audiostream_2eproto;
namespace com {
namespace audiostream {
namespace pb {
class AudioFormat;
struct AudioFormatDefaultTypeInternal;
extern AudioFormatDefaultTypeInternal _AudioFormat_default_instance_;
class DiscoveryBeacon;
struct DiscoveryBeaconDefaultTypeInternal;
extern DiscoveryBeaconDefaultTypeInternal _DiscoveryBeacon_default_instance_;
class MicControl;
struct MicControlDefaultTypeInternal;
extern MicControlDefaultTypeInternal _MicControl_default_instance_;
class StreamConfig;
struct StreamConfigDefaultTypeInternal;
extern StreamConfigDefaultTypeInternal _StreamConfig_default_instance_;
}  // namespace pb
}  // namespace audiostream
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::audiostream::pb::AudioFormat* Arena::CreateMaybeMessage<::com::audiostream::pb::AudioFormat>(Arena*);
template<> ::com::audiostream::pb::DiscoveryBeacon* Arena::CreateMaybeMessage<::com::audiostream::pb::DiscoveryBeacon>(Arena*);
template<> ::com::audiostream::pb::MicControl* Arena::CreateMaybeMessage<::com::audiostream::pb::MicControl>(Arena*);
template<> ::com::audiostream::pb::StreamConfig* Arena::CreateMaybeMessage<::com::audiostream::pb::StreamConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace audiostream {
namespace pb {

enum AudioCodec : int {
  CODEC_PCM = 0,
  CODEC_OPUS = 1,
  AudioCodec_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AudioCodec_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AudioCodec_IsValid(int value);
constexpr AudioCodec AudioCodec_MIN = CODEC_PCM;
constexpr AudioCodec AudioCodec_MAX = CODEC_OPUS;
constexpr int AudioCodec_ARRAYSIZE = AudioCodec_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AudioCodec_descriptor();
template<typename T>
inline const std::string& AudioCodec_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AudioCodec>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AudioCodec_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AudioCodec_descriptor(), enum_t_value);
}
inline bool AudioCodec_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AudioCodec* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AudioCodec>(
    AudioCodec_descriptor(), name, value);
}
enum AudioEncoding : int {
  ENCODING_INVALID = 0,
  ENCODING_PCM_FLOAT = 1,
  ENCODING_PCM_8BIT = 2,
  ENCODING_PCM_16BIT = 3,
  ENCODING_PCM_24BIT_PACKED = 4,
  ENCODING_PCM_32BIT = 5,
  AudioEncoding_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AudioEncoding_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AudioEncoding_IsValid(int value);
constexpr AudioEncoding AudioEncoding_MIN = ENCODING_INVALID;
constexpr AudioEncoding AudioEncoding_MAX = ENCODING_PCM_32BIT;
constexpr int AudioEncoding_ARRAYSIZE = AudioEncoding_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AudioEncoding_descriptor();
template<typename T>
inline const std::string& AudioEncoding_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AudioEncoding>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AudioEncoding_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AudioEncoding_descriptor(), enum_t_value);
}
inline bool AudioEncoding_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AudioEncoding* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AudioEncoding>(
    AudioEncoding_descriptor(), name, value);
}
// ===================================================================

class AudioFormat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.audiostream.pb.AudioFormat) */ {
 public:
  inline AudioFormat() : AudioFormat(nullptr) {}
  ~AudioFormat() override;
  explicit PROTOBUF_CONSTEXPR AudioFormat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AudioFormat(const AudioFormat& from);
  AudioFormat(AudioFormat&& from) noexcept
    : AudioFormat() {
    *this = ::std::move(from);
  }

  inline AudioFormat& operator=(const AudioFormat& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioFormat& operator=(AudioFormat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudioFormat& default_instance() {
    return *internal_default_instance();
  }
  static inline const AudioFormat* internal_default_instance() {
    return reinterpret_cast<const AudioFormat*>(
               &_AudioFormat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AudioFormat& a, AudioFormat& b) {
    a.Swap(&b);
  }
  inline void Swap(AudioFormat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudioFormat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AudioFormat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AudioFormat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AudioFormat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AudioFormat& from) {
    AudioFormat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AudioFormat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.audiostream.pb.AudioFormat";
  }
  protected:
  explicit AudioFormat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEncodingFieldNumber = 1,
    kChannelsFieldNumber = 2,
    kSampleRateFieldNumber = 3,
  };
  // .com.audiostream.pb.AudioEncoding encoding = 1;
  void clear_encoding();
  ::com::audiostream::pb::AudioEncoding encoding() const;
  void set_encoding(::com::audiostream::pb::AudioEncoding value);
  private:
  ::com::audiostream::pb::AudioEncoding _internal_encoding() const;
  void _internal_set_encoding(::com::audiostream::pb::AudioEncoding value);
  public:

  // int32 channels = 2;
  void clear_channels();
  int32_t channels() const;
  void set_channels(int32_t value);
  private:
  int32_t _internal_channels() const;
  void _internal_set_channels(int32_t value);
  public:

  // int32 sample_rate = 3;
  void clear_sample_rate();
  int32_t sample_rate() const;
  void set_sample_rate(int32_t value);
  private:
  int32_t _internal_sample_rate() const;
  void _internal_set_sample_rate(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:com.audiostream.pb.AudioFormat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int encoding_;
    int32_t channels_;
    int32_t sample_rate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_audiostream_2eproto;
};
// -------------------------------------------------------------------

class StreamConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.audiostream.pb.StreamConfig) */ {
 public:
  inline StreamConfig() : StreamConfig(nullptr) {}
  ~StreamConfig() override;
  explicit PROTOBUF_CONSTEXPR StreamConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamConfig(const StreamConfig& from);
  StreamConfig(StreamConfig&& from) noexcept
    : StreamConfig() {
    *this = ::std::move(from);
  }

  inline StreamConfig& operator=(const StreamConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamConfig& operator=(StreamConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamConfig* internal_default_instance() {
    return reinterpret_cast<const StreamConfig*>(
               &_StreamConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StreamConfig& a, StreamConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamConfig& from) {
    StreamConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.audiostream.pb.StreamConfig";
  }
  protected:
  explicit StreamConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFormatFieldNumber = 1,
    kCodecFieldNumber = 2,
    kOpusBitrateFieldNumber = 3,
    kOpusFrameSizeMsFieldNumber = 4,
    kTargetLatencyMsFieldNumber = 5,
  };
  // .com.audiostream.pb.AudioFormat format = 1;
  bool has_format() const;
  private:
  bool _internal_has_format() const;
  public:
  void clear_format();
  const ::com::audiostream::pb::AudioFormat& format() const;
  PROTOBUF_NODISCARD ::com::audiostream::pb::AudioFormat* release_format();
  ::com::audiostream::pb::AudioFormat* mutable_format();
  void set_allocated_format(::com::audiostream::pb::AudioFormat* format);
  private:
  const ::com::audiostream::pb::AudioFormat& _internal_format() const;
  ::com::audiostream::pb::AudioFormat* _internal_mutable_format();
  public:
  void unsafe_arena_set_allocated_format(
      ::com::audiostream::pb::AudioFormat* format);
  ::com::audiostream::pb::AudioFormat* unsafe_arena_release_format();

  // .com.audiostream.pb.AudioCodec codec = 2;
  void clear_codec();
  ::com::audiostream::pb::AudioCodec codec() const;
  void set_codec(::com::audiostream::pb::AudioCodec value);
  private:
  ::com::audiostream::pb::AudioCodec _internal_codec() const;
  void _internal_set_codec(::com::audiostream::pb::AudioCodec value);
  public:

  // int32 opus_bitrate = 3;
  void clear_opus_bitrate();
  int32_t opus_bitrate() const;
  void set_opus_bitrate(int32_t value);
  private:
  int32_t _internal_opus_bitrate() const;
  void _internal_set_opus_bitrate(int32_t value);
  public:

  // int32 opus_frame_size_ms = 4;
  void clear_opus_frame_size_ms();
  int32_t opus_frame_size_ms() const;
  void set_opus_frame_size_ms(int32_t value);
  private:
  int32_t _internal_opus_frame_size_ms() const;
  void _internal_set_opus_frame_size_ms(int32_t value);
  public:

  // int32 target_latency_ms = 5;
  void clear_target_latency_ms();
  int32_t target_latency_ms() const;
  void set_target_latency_ms(int32_t value);
  private:
  int32_t _internal_target_latency_ms() const;
  void _internal_set_target_latency_ms(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:com.audiostream.pb.StreamConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::com::audiostream::pb::AudioFormat* format_;
    int codec_;
    int32_t opus_bitrate_;
    int32_t opus_frame_size_ms_;
    int32_t target_latency_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_audiostream_2eproto;
};
// -------------------------------------------------------------------

class MicControl final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.audiostream.pb.MicControl) */ {
 public:
  inline MicControl() : MicControl(nullptr) {}
  ~MicControl() override;
  explicit PROTOBUF_CONSTEXPR MicControl(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MicControl(const MicControl& from);
  MicControl(MicControl&& from) noexcept
    : MicControl() {
    *this = ::std::move(from);
  }

  inline MicControl& operator=(const MicControl& from) {
    CopyFrom(from);
    return *this;
  }
  inline MicControl& operator=(MicControl&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MicControl& default_instance() {
    return *internal_default_instance();
  }
  static inline const MicControl* internal_default_instance() {
    return reinterpret_cast<const MicControl*>(
               &_MicControl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MicControl& a, MicControl& b) {
    a.Swap(&b);
  }
  inline void Swap(MicControl* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MicControl* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MicControl* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MicControl>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MicControl& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MicControl& from) {
    MicControl::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MicControl* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.audiostream.pb.MicControl";
  }
  protected:
  explicit MicControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConfigFieldNumber = 2,
    kStartFieldNumber = 1,
    kMicSourceFieldNumber = 3,
  };
  // .com.audiostream.pb.StreamConfig config = 2;
  bool has_config() const;
  private:
  bool _internal_has_config() const;
  public:
  void clear_config();
  const ::com::audiostream::pb::StreamConfig& config() const;
  PROTOBUF_NODISCARD ::com::audiostream::pb::StreamConfig* release_config();
  ::com::audiostream::pb::StreamConfig* mutable_config();
  void set_allocated_config(::com::audiostream::pb::StreamConfig* config);
  private:
  const ::com::audiostream::pb::StreamConfig& _internal_config() const;
  ::com::audiostream::pb::StreamConfig* _internal_mutable_config();
  public:
  void unsafe_arena_set_allocated_config(
      ::com::audiostream::pb::StreamConfig* config);
  ::com::audiostream::pb::StreamConfig* unsafe_arena_release_config();

  // bool start = 1;
  void clear_start();
  bool start() const;
  void set_start(bool value);
  private:
  bool _internal_start() const;
  void _internal_set_start(bool value);
  public:

  // int32 mic_source = 3;
  void clear_mic_source();
  int32_t mic_source() const;
  void set_mic_source(int32_t value);
  private:
  int32_t _internal_mic_source() const;
  void _internal_set_mic_source(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:com.audiostream.pb.MicControl)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::com::audiostream::pb::StreamConfig* config_;
    bool start_;
    int32_t mic_source_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_audiostream_2eproto;
};
// -------------------------------------------------------------------

class DiscoveryBeacon final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.audiostream.pb.DiscoveryBeacon) */ {
 public:
  inline DiscoveryBeacon() : DiscoveryBeacon(nullptr) {}
  ~DiscoveryBeacon() override;
  explicit PROTOBUF_CONSTEXPR DiscoveryBeacon(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DiscoveryBeacon(const DiscoveryBeacon& from);
  DiscoveryBeacon(DiscoveryBeacon&& from) noexcept
    : DiscoveryBeacon() {
    *this = ::std::move(from);
  }

  inline DiscoveryBeacon& operator=(const DiscoveryBeacon& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiscoveryBeacon& operator=(DiscoveryBeacon&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiscoveryBeacon& default_instance() {
    return *internal_default_instance();
  }
  static inline const DiscoveryBeacon* internal_default_instance() {
    return reinterpret_cast<const DiscoveryBeacon*>(
               &_DiscoveryBeacon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DiscoveryBeacon& a, DiscoveryBeacon& b) {
    a.Swap(&b);
  }
  inline void Swap(DiscoveryBeacon* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiscoveryBeacon* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiscoveryBeacon* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DiscoveryBeacon>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DiscoveryBeacon& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DiscoveryBeacon& from) {
    DiscoveryBeacon::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DiscoveryBeacon* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.audiostream.pb.DiscoveryBeacon";
  }
  protected:
  explicit DiscoveryBeacon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppNameFieldNumber = 1,
    kServerNameFieldNumber = 2,
    kVersionFieldNumber = 4,
    kIpAddressFieldNumber = 7,
    kPortFieldNumber = 3,
    kSupportsOpusFieldNumber = 5,
    kSupportsMicFieldNumber = 6,
  };
  // string app_name = 1;
  void clear_app_name();
  const std::string& app_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_app_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_app_name();
  PROTOBUF_NODISCARD std::string* release_app_name();
  void set_allocated_app_name(std::string* app_name);
  private:
  const std::string& _internal_app_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_name(const std::string& value);
  std::string* _internal_mutable_app_name();
  public:

  // string server_name = 2;
  void clear_server_name();
  const std::string& server_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_name();
  PROTOBUF_NODISCARD std::string* release_server_name();
  void set_allocated_server_name(std::string* server_name);
  private:
  const std::string& _internal_server_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_name(const std::string& value);
  std::string* _internal_mutable_server_name();
  public:

  // string version = 4;
  void clear_version();
  const std::string& version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_version();
  PROTOBUF_NODISCARD std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // string ip_address = 7;
  void clear_ip_address();
  const std::string& ip_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip_address();
  PROTOBUF_NODISCARD std::string* release_ip_address();
  void set_allocated_ip_address(std::string* ip_address);
  private:
  const std::string& _internal_ip_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip_address(const std::string& value);
  std::string* _internal_mutable_ip_address();
  public:

  // int32 port = 3;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // bool supports_opus = 5;
  void clear_supports_opus();
  bool supports_opus() const;
  void set_supports_opus(bool value);
  private:
  bool _internal_supports_opus() const;
  void _internal_set_supports_opus(bool value);
  public:

  // bool supports_mic = 6;
  void clear_supports_mic();
  bool supports_mic() const;
  void set_supports_mic(bool value);
  private:
  bool _internal_supports_mic() const;
  void _internal_set_supports_mic(bool value);
  public:

  // @@protoc_insertion_point(class_scope:com.audiostream.pb.DiscoveryBeacon)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_address_;
    int32_t port_;
    bool supports_opus_;
    bool supports_mic_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_audiostream_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AudioFormat

// .com.audiostream.pb.AudioEncoding encoding = 1;
inline void AudioFormat::clear_encoding() {
  _impl_.encoding_ = 0;
}
inline ::com::audiostream::pb::AudioEncoding AudioFormat::_internal_encoding() const {
  return static_cast< ::com::audiostream::pb::AudioEncoding >(_impl_.encoding_);
}
inline ::com::audiostream::pb::AudioEncoding AudioFormat::encoding() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.AudioFormat.encoding)
  return _internal_encoding();
}
inline void AudioFormat::_internal_set_encoding(::com::audiostream::pb::AudioEncoding value) {
  
  _impl_.encoding_ = value;
}
inline void AudioFormat::set_encoding(::com::audiostream::pb::AudioEncoding value) {
  _internal_set_encoding(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.AudioFormat.encoding)
}

// int32 channels = 2;
inline void AudioFormat::clear_channels() {
  _impl_.channels_ = 0;
}
inline int32_t AudioFormat::_internal_channels() const {
  return _impl_.channels_;
}
inline int32_t AudioFormat::channels() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.AudioFormat.channels)
  return _internal_channels();
}
inline void AudioFormat::_internal_set_channels(int32_t value) {
  
  _impl_.channels_ = value;
}
inline void AudioFormat::set_channels(int32_t value) {
  _internal_set_channels(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.AudioFormat.channels)
}

// int32 sample_rate = 3;
inline void AudioFormat::clear_sample_rate() {
  _impl_.sample_rate_ = 0;
}
inline int32_t AudioFormat::_internal_sample_rate() const {
  return _impl_.sample_rate_;
}
inline int32_t AudioFormat::sample_rate() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.AudioFormat.sample_rate)
  return _internal_sample_rate();
}
inline void AudioFormat::_internal_set_sample_rate(int32_t value) {
  
  _impl_.sample_rate_ = value;
}
inline void AudioFormat::set_sample_rate(int32_t value) {
  _internal_set_sample_rate(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.AudioFormat.sample_rate)
}

// -------------------------------------------------------------------

// StreamConfig

// .com.audiostream.pb.AudioFormat format = 1;
inline bool StreamConfig::_internal_has_format() const {
  return this != internal_default_instance() && _impl_.format_ != nullptr;
}
inline bool StreamConfig::has_format() const {
  return _internal_has_format();
}
inline void StreamConfig::clear_format() {
  if (GetArenaForAllocation() == nullptr && _impl_.format_ != nullptr) {
    delete _impl_.format_;
  }
  _impl_.format_ = nullptr;
}
inline const ::com::audiostream::pb::AudioFormat& StreamConfig::_internal_format() const {
  const ::com::audiostream::pb::AudioFormat* p = _impl_.format_;
  return p != nullptr ? *p : reinterpret_cast<const ::com::audiostream::pb::AudioFormat&>(
      ::com::audiostream::pb::_AudioFormat_default_instance_);
}
inline const ::com::audiostream::pb::AudioFormat& StreamConfig::format() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.StreamConfig.format)
  return _internal_format();
}
inline void StreamConfig::unsafe_arena_set_allocated_format(
    ::com::audiostream::pb::AudioFormat* format) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.format_);
  }
  _impl_.format_ = format;
  if (format) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.audiostream.pb.StreamConfig.format)
}
inline ::com::audiostream::pb::AudioFormat* StreamConfig::release_format() {
  
  ::com::audiostream::pb::AudioFormat* temp = _impl_.format_;
  _impl_.format_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::com::audiostream::pb::AudioFormat* StreamConfig::unsafe_arena_release_format() {
  // @@protoc_insertion_point(field_release:com.audiostream.pb.StreamConfig.format)
  
  ::com::audiostream::pb::AudioFormat* temp = _impl_.format_;
  _impl_.format_ = nullptr;
  return temp;
}
inline ::com::audiostream::pb::AudioFormat* StreamConfig::_internal_mutable_format() {
  
  if (_impl_.format_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::audiostream::pb::AudioFormat>(GetArenaForAllocation());
    _impl_.format_ = p;
  }
  return _impl_.format_;
}
inline ::com::audiostream::pb::AudioFormat* StreamConfig::mutable_format() {
  ::com::audiostream::pb::AudioFormat* _msg = _internal_mutable_format();
  // @@protoc_insertion_point(field_mutable:com.audiostream.pb.StreamConfig.format)
  return _msg;
}
inline void StreamConfig::set_allocated_format(::com::audiostream::pb::AudioFormat* format) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.format_;
  }
  if (format) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(format);
    if (message_arena != submessage_arena) {
      format = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, format, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.format_ = format;
  // @@protoc_insertion_point(field_set_allocated:com.audiostream.pb.StreamConfig.format)
}

// .com.audiostream.pb.AudioCodec codec = 2;
inline void StreamConfig::clear_codec() {
  _impl_.codec_ = 0;
}
inline ::com::audiostream::pb::AudioCodec StreamConfig::_internal_codec() const {
  return static_cast< ::com::audiostream::pb::AudioCodec >(_impl_.codec_);
}
inline ::com::audiostream::pb::AudioCodec StreamConfig::codec() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.StreamConfig.codec)
  return _internal_codec();
}
inline void StreamConfig::_internal_set_codec(::com::audiostream::pb::AudioCodec value) {
  
  _impl_.codec_ = value;
}
inline void StreamConfig::set_codec(::com::audiostream::pb::AudioCodec value) {
  _internal_set_codec(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.StreamConfig.codec)
}

// int32 opus_bitrate = 3;
inline void StreamConfig::clear_opus_bitrate() {
  _impl_.opus_bitrate_ = 0;
}
inline int32_t StreamConfig::_internal_opus_bitrate() const {
  return _impl_.opus_bitrate_;
}
inline int32_t StreamConfig::opus_bitrate() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.StreamConfig.opus_bitrate)
  return _internal_opus_bitrate();
}
inline void StreamConfig::_internal_set_opus_bitrate(int32_t value) {
  
  _impl_.opus_bitrate_ = value;
}
inline void StreamConfig::set_opus_bitrate(int32_t value) {
  _internal_set_opus_bitrate(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.StreamConfig.opus_bitrate)
}

// int32 opus_frame_size_ms = 4;
inline void StreamConfig::clear_opus_frame_size_ms() {
  _impl_.opus_frame_size_ms_ = 0;
}
inline int32_t StreamConfig::_internal_opus_frame_size_ms() const {
  return _impl_.opus_frame_size_ms_;
}
inline int32_t StreamConfig::opus_frame_size_ms() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.StreamConfig.opus_frame_size_ms)
  return _internal_opus_frame_size_ms();
}
inline void StreamConfig::_internal_set_opus_frame_size_ms(int32_t value) {
  
  _impl_.opus_frame_size_ms_ = value;
}
inline void StreamConfig::set_opus_frame_size_ms(int32_t value) {
  _internal_set_opus_frame_size_ms(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.StreamConfig.opus_frame_size_ms)
}

// int32 target_latency_ms = 5;
inline void StreamConfig::clear_target_latency_ms() {
  _impl_.target_latency_ms_ = 0;
}
inline int32_t StreamConfig::_internal_target_latency_ms() const {
  return _impl_.target_latency_ms_;
}
inline int32_t StreamConfig::target_latency_ms() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.StreamConfig.target_latency_ms)
  return _internal_target_latency_ms();
}
inline void StreamConfig::_internal_set_target_latency_ms(int32_t value) {
  
  _impl_.target_latency_ms_ = value;
}
inline void StreamConfig::set_target_latency_ms(int32_t value) {
  _internal_set_target_latency_ms(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.StreamConfig.target_latency_ms)
}

// -------------------------------------------------------------------

// MicControl

// bool start = 1;
inline void MicControl::clear_start() {
  _impl_.start_ = false;
}
inline bool MicControl::_internal_start() const {
  return _impl_.start_;
}
inline bool MicControl::start() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.MicControl.start)
  return _internal_start();
}
inline void MicControl::_internal_set_start(bool value) {
  
  _impl_.start_ = value;
}
inline void MicControl::set_start(bool value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.MicControl.start)
}

// .com.audiostream.pb.StreamConfig config = 2;
inline bool MicControl::_internal_has_config() const {
  return this != internal_default_instance() && _impl_.config_ != nullptr;
}
inline bool MicControl::has_config() const {
  return _internal_has_config();
}
inline void MicControl::clear_config() {
  if (GetArenaForAllocation() == nullptr && _impl_.config_ != nullptr) {
    delete _impl_.config_;
  }
  _impl_.config_ = nullptr;
}
inline const ::com::audiostream::pb::StreamConfig& MicControl::_internal_config() const {
  const ::com::audiostream::pb::StreamConfig* p = _impl_.config_;
  return p != nullptr ? *p : reinterpret_cast<const ::com::audiostream::pb::StreamConfig&>(
      ::com::audiostream::pb::_StreamConfig_default_instance_);
}
inline const ::com::audiostream::pb::StreamConfig& MicControl::config() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.MicControl.config)
  return _internal_config();
}
inline void MicControl::unsafe_arena_set_allocated_config(
    ::com::audiostream::pb::StreamConfig* config) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.config_);
  }
  _impl_.config_ = config;
  if (config) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.audiostream.pb.MicControl.config)
}
inline ::com::audiostream::pb::StreamConfig* MicControl::release_config() {
  
  ::com::audiostream::pb::StreamConfig* temp = _impl_.config_;
  _impl_.config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::com::audiostream::pb::StreamConfig* MicControl::unsafe_arena_release_config() {
  // @@protoc_insertion_point(field_release:com.audiostream.pb.MicControl.config)
  
  ::com::audiostream::pb::StreamConfig* temp = _impl_.config_;
  _impl_.config_ = nullptr;
  return temp;
}
inline ::com::audiostream::pb::StreamConfig* MicControl::_internal_mutable_config() {
  
  if (_impl_.config_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::audiostream::pb::StreamConfig>(GetArenaForAllocation());
    _impl_.config_ = p;
  }
  return _impl_.config_;
}
inline ::com::audiostream::pb::StreamConfig* MicControl::mutable_config() {
  ::com::audiostream::pb::StreamConfig* _msg = _internal_mutable_config();
  // @@protoc_insertion_point(field_mutable:com.audiostream.pb.MicControl.config)
  return _msg;
}
inline void MicControl::set_allocated_config(::com::audiostream::pb::StreamConfig* config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.config_;
  }
  if (config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(config);
    if (message_arena != submessage_arena) {
      config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.config_ = config;
  // @@protoc_insertion_point(field_set_allocated:com.audiostream.pb.MicControl.config)
}

// int32 mic_source = 3;
inline void MicControl::clear_mic_source() {
  _impl_.mic_source_ = 0;
}
inline int32_t MicControl::_internal_mic_source() const {
  return _impl_.mic_source_;
}
inline int32_t MicControl::mic_source() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.MicControl.mic_source)
  return _internal_mic_source();
}
inline void MicControl::_internal_set_mic_source(int32_t value) {
  
  _impl_.mic_source_ = value;
}
inline void MicControl::set_mic_source(int32_t value) {
  _internal_set_mic_source(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.MicControl.mic_source)
}

// -------------------------------------------------------------------

// DiscoveryBeacon

// string app_name = 1;
inline void DiscoveryBeacon::clear_app_name() {
  _impl_.app_name_.ClearToEmpty();
}
inline const std::string& DiscoveryBeacon::app_name() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.DiscoveryBeacon.app_name)
  return _internal_app_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiscoveryBeacon::set_app_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.app_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.audiostream.pb.DiscoveryBeacon.app_name)
}
inline std::string* DiscoveryBeacon::mutable_app_name() {
  std::string* _s = _internal_mutable_app_name();
  // @@protoc_insertion_point(field_mutable:com.audiostream.pb.DiscoveryBeacon.app_name)
  return _s;
}
inline const std::string& DiscoveryBeacon::_internal_app_name() const {
  return _impl_.app_name_.Get();
}
inline void DiscoveryBeacon::_internal_set_app_name(const std::string& value) {
  
  _impl_.app_name_.Set(value, GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::_internal_mutable_app_name() {
  
  return _impl_.app_name_.Mutable(GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::release_app_name() {
  // @@protoc_insertion_point(field_release:com.audiostream.pb.DiscoveryBeacon.app_name)
  return _impl_.app_name_.Release();
}
inline void DiscoveryBeacon::set_allocated_app_name(std::string* app_name) {
  if (app_name != nullptr) {
    
  } else {
    
  }
  _impl_.app_name_.SetAllocated(app_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.app_name_.IsDefault()) {
    _impl_.app_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.audiostream.pb.DiscoveryBeacon.app_name)
}

// string server_name = 2;
inline void DiscoveryBeacon::clear_server_name() {
  _impl_.server_name_.ClearToEmpty();
}
inline const std::string& DiscoveryBeacon::server_name() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.DiscoveryBeacon.server_name)
  return _internal_server_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiscoveryBeacon::set_server_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.audiostream.pb.DiscoveryBeacon.server_name)
}
inline std::string* DiscoveryBeacon::mutable_server_name() {
  std::string* _s = _internal_mutable_server_name();
  // @@protoc_insertion_point(field_mutable:com.audiostream.pb.DiscoveryBeacon.server_name)
  return _s;
}
inline const std::string& DiscoveryBeacon::_internal_server_name() const {
  return _impl_.server_name_.Get();
}
inline void DiscoveryBeacon::_internal_set_server_name(const std::string& value) {
  
  _impl_.server_name_.Set(value, GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::_internal_mutable_server_name() {
  
  return _impl_.server_name_.Mutable(GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::release_server_name() {
  // @@protoc_insertion_point(field_release:com.audiostream.pb.DiscoveryBeacon.server_name)
  return _impl_.server_name_.Release();
}
inline void DiscoveryBeacon::set_allocated_server_name(std::string* server_name) {
  if (server_name != nullptr) {
    
  } else {
    
  }
  _impl_.server_name_.SetAllocated(server_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_name_.IsDefault()) {
    _impl_.server_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.audiostream.pb.DiscoveryBeacon.server_name)
}

// int32 port = 3;
inline void DiscoveryBeacon::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t DiscoveryBeacon::_internal_port() const {
  return _impl_.port_;
}
inline int32_t DiscoveryBeacon::port() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.DiscoveryBeacon.port)
  return _internal_port();
}
inline void DiscoveryBeacon::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void DiscoveryBeacon::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.DiscoveryBeacon.port)
}

// string version = 4;
inline void DiscoveryBeacon::clear_version() {
  _impl_.version_.ClearToEmpty();
}
inline const std::string& DiscoveryBeacon::version() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.DiscoveryBeacon.version)
  return _internal_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiscoveryBeacon::set_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.audiostream.pb.DiscoveryBeacon.version)
}
inline std::string* DiscoveryBeacon::mutable_version() {
  std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:com.audiostream.pb.DiscoveryBeacon.version)
  return _s;
}
inline const std::string& DiscoveryBeacon::_internal_version() const {
  return _impl_.version_.Get();
}
inline void DiscoveryBeacon::_internal_set_version(const std::string& value) {
  
  _impl_.version_.Set(value, GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::_internal_mutable_version() {
  
  return _impl_.version_.Mutable(GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::release_version() {
  // @@protoc_insertion_point(field_release:com.audiostream.pb.DiscoveryBeacon.version)
  return _impl_.version_.Release();
}
inline void DiscoveryBeacon::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  _impl_.version_.SetAllocated(version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.version_.IsDefault()) {
    _impl_.version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.audiostream.pb.DiscoveryBeacon.version)
}

// bool supports_opus = 5;
inline void DiscoveryBeacon::clear_supports_opus() {
  _impl_.supports_opus_ = false;
}
inline bool DiscoveryBeacon::_internal_supports_opus() const {
  return _impl_.supports_opus_;
}
inline bool DiscoveryBeacon::supports_opus() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.DiscoveryBeacon.supports_opus)
  return _internal_supports_opus();
}
inline void DiscoveryBeacon::_internal_set_supports_opus(bool value) {
  
  _impl_.supports_opus_ = value;
}
inline void DiscoveryBeacon::set_supports_opus(bool value) {
  _internal_set_supports_opus(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.DiscoveryBeacon.supports_opus)
}

// bool supports_mic = 6;
inline void DiscoveryBeacon::clear_supports_mic() {
  _impl_.supports_mic_ = false;
}
inline bool DiscoveryBeacon::_internal_supports_mic() const {
  return _impl_.supports_mic_;
}
inline bool DiscoveryBeacon::supports_mic() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.DiscoveryBeacon.supports_mic)
  return _internal_supports_mic();
}
inline void DiscoveryBeacon::_internal_set_supports_mic(bool value) {
  
  _impl_.supports_mic_ = value;
}
inline void DiscoveryBeacon::set_supports_mic(bool value) {
  _internal_set_supports_mic(value);
  // @@protoc_insertion_point(field_set:com.audiostream.pb.DiscoveryBeacon.supports_mic)
}

// string ip_address = 7;
inline void DiscoveryBeacon::clear_ip_address() {
  _impl_.ip_address_.ClearToEmpty();
}
inline const std::string& DiscoveryBeacon::ip_address() const {
  // @@protoc_insertion_point(field_get:com.audiostream.pb.DiscoveryBeacon.ip_address)
  return _internal_ip_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiscoveryBeacon::set_ip_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.audiostream.pb.DiscoveryBeacon.ip_address)
}
inline std::string* DiscoveryBeacon::mutable_ip_address() {
  std::string* _s = _internal_mutable_ip_address();
  // @@protoc_insertion_point(field_mutable:com.audiostream.pb.DiscoveryBeacon.ip_address)
  return _s;
}
inline const std::string& DiscoveryBeacon::_internal_ip_address() const {
  return _impl_.ip_address_.Get();
}
inline void DiscoveryBeacon::_internal_set_ip_address(const std::string& value) {
  
  _impl_.ip_address_.Set(value, GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::_internal_mutable_ip_address() {
  
  return _impl_.ip_address_.Mutable(GetArenaForAllocation());
}
inline std::string* DiscoveryBeacon::release_ip_address() {
  // @@protoc_insertion_point(field_release:com.audiostream.pb.DiscoveryBeacon.ip_address)
  return _impl_.ip_address_.Release();
}
inline void DiscoveryBeacon::set_allocated_ip_address(std::string* ip_address) {
  if (ip_address != nullptr) {
    
  } else {
    
  }
  _impl_.ip_address_.SetAllocated(ip_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.audiostream.pb.DiscoveryBeacon.ip_address)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace audiostream
}  // namespace com

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::com::audiostream::pb::AudioCodec> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::audiostream::pb::AudioCodec>() {
  return ::com::audiostream::pb::AudioCodec_descriptor();
}
template <> struct is_proto_enum< ::com::audiostream::pb::AudioEncoding> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::audiostream::pb::AudioEncoding>() {
  return ::com::audiostream::pb::AudioEncoding_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_audiostream_2eproto
