// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audiostream.proto

#include "audiostream.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace com {
namespace audiostream {
namespace pb {
PROTOBUF_CONSTEXPR AudioFormat::AudioFormat(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.encoding_)*/0
  , /*decltype(_impl_.channels_)*/0
  , /*decltype(_impl_.sample_rate_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AudioFormatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AudioFormatDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AudioFormatDefaultTypeInternal() {}
  union {
    AudioFormat _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AudioFormatDefaultTypeInternal _AudioFormat_default_instance_;
PROTOBUF_CONSTEXPR StreamConfig::StreamConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.format_)*/nullptr
  , /*decltype(_impl_.codec_)*/0
  , /*decltype(_impl_.opus_bitrate_)*/0
  , /*decltype(_impl_.opus_frame_size_ms_)*/0
  , /*decltype(_impl_.target_latency_ms_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StreamConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamConfigDefaultTypeInternal() {}
  union {
    StreamConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamConfigDefaultTypeInternal _StreamConfig_default_instance_;
PROTOBUF_CONSTEXPR MicControl::MicControl(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.config_)*/nullptr
  , /*decltype(_impl_.start_)*/false
  , /*decltype(_impl_.mic_source_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MicControlDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MicControlDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MicControlDefaultTypeInternal() {}
  union {
    MicControl _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MicControlDefaultTypeInternal _MicControl_default_instance_;
PROTOBUF_CONSTEXPR DiscoveryBeacon::DiscoveryBeacon(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.app_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.server_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ip_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.port_)*/0
  , /*decltype(_impl_.supports_opus_)*/false
  , /*decltype(_impl_.supports_mic_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DiscoveryBeaconDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DiscoveryBeaconDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DiscoveryBeaconDefaultTypeInternal() {}
  union {
    DiscoveryBeacon _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DiscoveryBeaconDefaultTypeInternal _DiscoveryBeacon_default_instance_;
}  // namespace pb
}  // namespace audiostream
}  // namespace com
static ::_pb::Metadata file_level_metadata_audiostream_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_audiostream_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_audiostream_2eproto = nullptr;

const uint32_t TableStruct_audiostream_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::AudioFormat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::AudioFormat, _impl_.encoding_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::AudioFormat, _impl_.channels_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::AudioFormat, _impl_.sample_rate_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::StreamConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::StreamConfig, _impl_.format_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::StreamConfig, _impl_.codec_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::StreamConfig, _impl_.opus_bitrate_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::StreamConfig, _impl_.opus_frame_size_ms_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::StreamConfig, _impl_.target_latency_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::MicControl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::MicControl, _impl_.start_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::MicControl, _impl_.config_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::MicControl, _impl_.mic_source_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _impl_.app_name_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _impl_.server_name_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _impl_.version_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _impl_.supports_opus_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _impl_.supports_mic_),
  PROTOBUF_FIELD_OFFSET(::com::audiostream::pb::DiscoveryBeacon, _impl_.ip_address_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::com::audiostream::pb::AudioFormat)},
  { 9, -1, -1, sizeof(::com::audiostream::pb::StreamConfig)},
  { 20, -1, -1, sizeof(::com::audiostream::pb::MicControl)},
  { 29, -1, -1, sizeof(::com::audiostream::pb::DiscoveryBeacon)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::com::audiostream::pb::_AudioFormat_default_instance_._instance,
  &::com::audiostream::pb::_StreamConfig_default_instance_._instance,
  &::com::audiostream::pb::_MicControl_default_instance_._instance,
  &::com::audiostream::pb::_DiscoveryBeacon_default_instance_._instance,
};

const char descriptor_table_protodef_audiostream_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021audiostream.proto\022\022com.audiostream.pb\""
  "i\n\013AudioFormat\0223\n\010encoding\030\001 \001(\0162!.com.a"
  "udiostream.pb.AudioEncoding\022\020\n\010channels\030"
  "\002 \001(\005\022\023\n\013sample_rate\030\003 \001(\005\"\273\001\n\014StreamCon"
  "fig\022/\n\006format\030\001 \001(\0132\037.com.audiostream.pb"
  ".AudioFormat\022-\n\005codec\030\002 \001(\0162\036.com.audios"
  "tream.pb.AudioCodec\022\024\n\014opus_bitrate\030\003 \001("
  "\005\022\032\n\022opus_frame_size_ms\030\004 \001(\005\022\031\n\021target_"
  "latency_ms\030\005 \001(\005\"a\n\nMicControl\022\r\n\005start\030"
  "\001 \001(\010\0220\n\006config\030\002 \001(\0132 .com.audiostream."
  "pb.StreamConfig\022\022\n\nmic_source\030\003 \001(\005\"\230\001\n\017"
  "DiscoveryBeacon\022\020\n\010app_name\030\001 \001(\t\022\023\n\013ser"
  "ver_name\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022\017\n\007version\030"
  "\004 \001(\t\022\025\n\rsupports_opus\030\005 \001(\010\022\024\n\014supports"
  "_mic\030\006 \001(\010\022\022\n\nip_address\030\007 \001(\t*+\n\nAudioC"
  "odec\022\r\n\tCODEC_PCM\020\000\022\016\n\nCODEC_OPUS\020\001*\243\001\n\r"
  "AudioEncoding\022\024\n\020ENCODING_INVALID\020\000\022\026\n\022E"
  "NCODING_PCM_FLOAT\020\001\022\025\n\021ENCODING_PCM_8BIT"
  "\020\002\022\026\n\022ENCODING_PCM_16BIT\020\003\022\035\n\031ENCODING_P"
  "CM_24BIT_PACKED\020\004\022\026\n\022ENCODING_PCM_32BIT\020"
  "\005B*\n\026com.audiostream.app.pbB\020AudioStream"
  "Protob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_audiostream_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_audiostream_2eproto = {
    false, false, 853, descriptor_table_protodef_audiostream_2eproto,
    "audiostream.proto",
    &descriptor_table_audiostream_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_audiostream_2eproto::offsets,
    file_level_metadata_audiostream_2eproto, file_level_enum_descriptors_audiostream_2eproto,
    file_level_service_descriptors_audiostream_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_audiostream_2eproto_getter() {
  return &descriptor_table_audiostream_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_audiostream_2eproto(&descriptor_table_audiostream_2eproto);
namespace com {
namespace audiostream {
namespace pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AudioCodec_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_audiostream_2eproto);
  return file_level_enum_descriptors_audiostream_2eproto[0];
}
bool AudioCodec_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AudioEncoding_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_audiostream_2eproto);
  return file_level_enum_descriptors_audiostream_2eproto[1];
}
bool AudioEncoding_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class AudioFormat::_Internal {
 public:
};

AudioFormat::AudioFormat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:com.audiostream.pb.AudioFormat)
}
AudioFormat::AudioFormat(const AudioFormat& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AudioFormat* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.encoding_){}
    , decltype(_impl_.channels_){}
    , decltype(_impl_.sample_rate_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.encoding_, &from._impl_.encoding_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sample_rate_) -
    reinterpret_cast<char*>(&_impl_.encoding_)) + sizeof(_impl_.sample_rate_));
  // @@protoc_insertion_point(copy_constructor:com.audiostream.pb.AudioFormat)
}

inline void AudioFormat::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.encoding_){0}
    , decltype(_impl_.channels_){0}
    , decltype(_impl_.sample_rate_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AudioFormat::~AudioFormat() {
  // @@protoc_insertion_point(destructor:com.audiostream.pb.AudioFormat)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AudioFormat::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AudioFormat::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AudioFormat::Clear() {
// @@protoc_insertion_point(message_clear_start:com.audiostream.pb.AudioFormat)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.encoding_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.sample_rate_) -
      reinterpret_cast<char*>(&_impl_.encoding_)) + sizeof(_impl_.sample_rate_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AudioFormat::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .com.audiostream.pb.AudioEncoding encoding = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_encoding(static_cast<::com::audiostream::pb::AudioEncoding>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 channels = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.channels_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 sample_rate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.sample_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AudioFormat::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.audiostream.pb.AudioFormat)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.audiostream.pb.AudioEncoding encoding = 1;
  if (this->_internal_encoding() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_encoding(), target);
  }

  // int32 channels = 2;
  if (this->_internal_channels() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_channels(), target);
  }

  // int32 sample_rate = 3;
  if (this->_internal_sample_rate() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_sample_rate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.audiostream.pb.AudioFormat)
  return target;
}

size_t AudioFormat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.audiostream.pb.AudioFormat)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .com.audiostream.pb.AudioEncoding encoding = 1;
  if (this->_internal_encoding() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_encoding());
  }

  // int32 channels = 2;
  if (this->_internal_channels() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_channels());
  }

  // int32 sample_rate = 3;
  if (this->_internal_sample_rate() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_sample_rate());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AudioFormat::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AudioFormat::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AudioFormat::GetClassData() const { return &_class_data_; }


void AudioFormat::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AudioFormat*>(&to_msg);
  auto& from = static_cast<const AudioFormat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.audiostream.pb.AudioFormat)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_encoding() != 0) {
    _this->_internal_set_encoding(from._internal_encoding());
  }
  if (from._internal_channels() != 0) {
    _this->_internal_set_channels(from._internal_channels());
  }
  if (from._internal_sample_rate() != 0) {
    _this->_internal_set_sample_rate(from._internal_sample_rate());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AudioFormat::CopyFrom(const AudioFormat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.audiostream.pb.AudioFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioFormat::IsInitialized() const {
  return true;
}

void AudioFormat::InternalSwap(AudioFormat* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AudioFormat, _impl_.sample_rate_)
      + sizeof(AudioFormat::_impl_.sample_rate_)
      - PROTOBUF_FIELD_OFFSET(AudioFormat, _impl_.encoding_)>(
          reinterpret_cast<char*>(&_impl_.encoding_),
          reinterpret_cast<char*>(&other->_impl_.encoding_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AudioFormat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_audiostream_2eproto_getter, &descriptor_table_audiostream_2eproto_once,
      file_level_metadata_audiostream_2eproto[0]);
}

// ===================================================================

class StreamConfig::_Internal {
 public:
  static const ::com::audiostream::pb::AudioFormat& format(const StreamConfig* msg);
};

const ::com::audiostream::pb::AudioFormat&
StreamConfig::_Internal::format(const StreamConfig* msg) {
  return *msg->_impl_.format_;
}
StreamConfig::StreamConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:com.audiostream.pb.StreamConfig)
}
StreamConfig::StreamConfig(const StreamConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StreamConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.format_){nullptr}
    , decltype(_impl_.codec_){}
    , decltype(_impl_.opus_bitrate_){}
    , decltype(_impl_.opus_frame_size_ms_){}
    , decltype(_impl_.target_latency_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_format()) {
    _this->_impl_.format_ = new ::com::audiostream::pb::AudioFormat(*from._impl_.format_);
  }
  ::memcpy(&_impl_.codec_, &from._impl_.codec_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.target_latency_ms_) -
    reinterpret_cast<char*>(&_impl_.codec_)) + sizeof(_impl_.target_latency_ms_));
  // @@protoc_insertion_point(copy_constructor:com.audiostream.pb.StreamConfig)
}

inline void StreamConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.format_){nullptr}
    , decltype(_impl_.codec_){0}
    , decltype(_impl_.opus_bitrate_){0}
    , decltype(_impl_.opus_frame_size_ms_){0}
    , decltype(_impl_.target_latency_ms_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StreamConfig::~StreamConfig() {
  // @@protoc_insertion_point(destructor:com.audiostream.pb.StreamConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StreamConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.format_;
}

void StreamConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StreamConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:com.audiostream.pb.StreamConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.format_ != nullptr) {
    delete _impl_.format_;
  }
  _impl_.format_ = nullptr;
  ::memset(&_impl_.codec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.target_latency_ms_) -
      reinterpret_cast<char*>(&_impl_.codec_)) + sizeof(_impl_.target_latency_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .com.audiostream.pb.AudioFormat format = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_format(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .com.audiostream.pb.AudioCodec codec = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_codec(static_cast<::com::audiostream::pb::AudioCodec>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 opus_bitrate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.opus_bitrate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 opus_frame_size_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.opus_frame_size_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 target_latency_ms = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.target_latency_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.audiostream.pb.StreamConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.audiostream.pb.AudioFormat format = 1;
  if (this->_internal_has_format()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::format(this),
        _Internal::format(this).GetCachedSize(), target, stream);
  }

  // .com.audiostream.pb.AudioCodec codec = 2;
  if (this->_internal_codec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_codec(), target);
  }

  // int32 opus_bitrate = 3;
  if (this->_internal_opus_bitrate() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_opus_bitrate(), target);
  }

  // int32 opus_frame_size_ms = 4;
  if (this->_internal_opus_frame_size_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_opus_frame_size_ms(), target);
  }

  // int32 target_latency_ms = 5;
  if (this->_internal_target_latency_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_target_latency_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.audiostream.pb.StreamConfig)
  return target;
}

size_t StreamConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.audiostream.pb.StreamConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .com.audiostream.pb.AudioFormat format = 1;
  if (this->_internal_has_format()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.format_);
  }

  // .com.audiostream.pb.AudioCodec codec = 2;
  if (this->_internal_codec() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_codec());
  }

  // int32 opus_bitrate = 3;
  if (this->_internal_opus_bitrate() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_opus_bitrate());
  }

  // int32 opus_frame_size_ms = 4;
  if (this->_internal_opus_frame_size_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_opus_frame_size_ms());
  }

  // int32 target_latency_ms = 5;
  if (this->_internal_target_latency_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_target_latency_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StreamConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamConfig::GetClassData() const { return &_class_data_; }


void StreamConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StreamConfig*>(&to_msg);
  auto& from = static_cast<const StreamConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.audiostream.pb.StreamConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_format()) {
    _this->_internal_mutable_format()->::com::audiostream::pb::AudioFormat::MergeFrom(
        from._internal_format());
  }
  if (from._internal_codec() != 0) {
    _this->_internal_set_codec(from._internal_codec());
  }
  if (from._internal_opus_bitrate() != 0) {
    _this->_internal_set_opus_bitrate(from._internal_opus_bitrate());
  }
  if (from._internal_opus_frame_size_ms() != 0) {
    _this->_internal_set_opus_frame_size_ms(from._internal_opus_frame_size_ms());
  }
  if (from._internal_target_latency_ms() != 0) {
    _this->_internal_set_target_latency_ms(from._internal_target_latency_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamConfig::CopyFrom(const StreamConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.audiostream.pb.StreamConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamConfig::IsInitialized() const {
  return true;
}

void StreamConfig::InternalSwap(StreamConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StreamConfig, _impl_.target_latency_ms_)
      + sizeof(StreamConfig::_impl_.target_latency_ms_)
      - PROTOBUF_FIELD_OFFSET(StreamConfig, _impl_.format_)>(
          reinterpret_cast<char*>(&_impl_.format_),
          reinterpret_cast<char*>(&other->_impl_.format_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_audiostream_2eproto_getter, &descriptor_table_audiostream_2eproto_once,
      file_level_metadata_audiostream_2eproto[1]);
}

// ===================================================================

class MicControl::_Internal {
 public:
  static const ::com::audiostream::pb::StreamConfig& config(const MicControl* msg);
};

const ::com::audiostream::pb::StreamConfig&
MicControl::_Internal::config(const MicControl* msg) {
  return *msg->_impl_.config_;
}
MicControl::MicControl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:com.audiostream.pb.MicControl)
}
MicControl::MicControl(const MicControl& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MicControl* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.config_){nullptr}
    , decltype(_impl_.start_){}
    , decltype(_impl_.mic_source_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_config()) {
    _this->_impl_.config_ = new ::com::audiostream::pb::StreamConfig(*from._impl_.config_);
  }
  ::memcpy(&_impl_.start_, &from._impl_.start_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mic_source_) -
    reinterpret_cast<char*>(&_impl_.start_)) + sizeof(_impl_.mic_source_));
  // @@protoc_insertion_point(copy_constructor:com.audiostream.pb.MicControl)
}

inline void MicControl::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.config_){nullptr}
    , decltype(_impl_.start_){false}
    , decltype(_impl_.mic_source_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MicControl::~MicControl() {
  // @@protoc_insertion_point(destructor:com.audiostream.pb.MicControl)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MicControl::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.config_;
}

void MicControl::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MicControl::Clear() {
// @@protoc_insertion_point(message_clear_start:com.audiostream.pb.MicControl)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.config_ != nullptr) {
    delete _impl_.config_;
  }
  _impl_.config_ = nullptr;
  ::memset(&_impl_.start_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mic_source_) -
      reinterpret_cast<char*>(&_impl_.start_)) + sizeof(_impl_.mic_source_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MicControl::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool start = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.start_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .com.audiostream.pb.StreamConfig config = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_config(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mic_source = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.mic_source_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MicControl::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.audiostream.pb.MicControl)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool start = 1;
  if (this->_internal_start() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_start(), target);
  }

  // .com.audiostream.pb.StreamConfig config = 2;
  if (this->_internal_has_config()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::config(this),
        _Internal::config(this).GetCachedSize(), target, stream);
  }

  // int32 mic_source = 3;
  if (this->_internal_mic_source() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_mic_source(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.audiostream.pb.MicControl)
  return target;
}

size_t MicControl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.audiostream.pb.MicControl)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .com.audiostream.pb.StreamConfig config = 2;
  if (this->_internal_has_config()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.config_);
  }

  // bool start = 1;
  if (this->_internal_start() != 0) {
    total_size += 1 + 1;
  }

  // int32 mic_source = 3;
  if (this->_internal_mic_source() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mic_source());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MicControl::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MicControl::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MicControl::GetClassData() const { return &_class_data_; }


void MicControl::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MicControl*>(&to_msg);
  auto& from = static_cast<const MicControl&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.audiostream.pb.MicControl)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_config()) {
    _this->_internal_mutable_config()->::com::audiostream::pb::StreamConfig::MergeFrom(
        from._internal_config());
  }
  if (from._internal_start() != 0) {
    _this->_internal_set_start(from._internal_start());
  }
  if (from._internal_mic_source() != 0) {
    _this->_internal_set_mic_source(from._internal_mic_source());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MicControl::CopyFrom(const MicControl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.audiostream.pb.MicControl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MicControl::IsInitialized() const {
  return true;
}

void MicControl::InternalSwap(MicControl* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MicControl, _impl_.mic_source_)
      + sizeof(MicControl::_impl_.mic_source_)
      - PROTOBUF_FIELD_OFFSET(MicControl, _impl_.config_)>(
          reinterpret_cast<char*>(&_impl_.config_),
          reinterpret_cast<char*>(&other->_impl_.config_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MicControl::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_audiostream_2eproto_getter, &descriptor_table_audiostream_2eproto_once,
      file_level_metadata_audiostream_2eproto[2]);
}

// ===================================================================

class DiscoveryBeacon::_Internal {
 public:
};

DiscoveryBeacon::DiscoveryBeacon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:com.audiostream.pb.DiscoveryBeacon)
}
DiscoveryBeacon::DiscoveryBeacon(const DiscoveryBeacon& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DiscoveryBeacon* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.app_name_){}
    , decltype(_impl_.server_name_){}
    , decltype(_impl_.version_){}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.supports_opus_){}
    , decltype(_impl_.supports_mic_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.app_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_app_name().empty()) {
    _this->_impl_.app_name_.Set(from._internal_app_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.server_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.server_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_server_name().empty()) {
    _this->_impl_.server_name_.Set(from._internal_server_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_version().empty()) {
    _this->_impl_.version_.Set(from._internal_version(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip_address().empty()) {
    _this->_impl_.ip_address_.Set(from._internal_ip_address(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.port_, &from._impl_.port_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.supports_mic_) -
    reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.supports_mic_));
  // @@protoc_insertion_point(copy_constructor:com.audiostream.pb.DiscoveryBeacon)
}

inline void DiscoveryBeacon::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.app_name_){}
    , decltype(_impl_.server_name_){}
    , decltype(_impl_.version_){}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.port_){0}
    , decltype(_impl_.supports_opus_){false}
    , decltype(_impl_.supports_mic_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.app_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.server_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.server_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DiscoveryBeacon::~DiscoveryBeacon() {
  // @@protoc_insertion_point(destructor:com.audiostream.pb.DiscoveryBeacon)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DiscoveryBeacon::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.app_name_.Destroy();
  _impl_.server_name_.Destroy();
  _impl_.version_.Destroy();
  _impl_.ip_address_.Destroy();
}

void DiscoveryBeacon::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DiscoveryBeacon::Clear() {
// @@protoc_insertion_point(message_clear_start:com.audiostream.pb.DiscoveryBeacon)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.app_name_.ClearToEmpty();
  _impl_.server_name_.ClearToEmpty();
  _impl_.version_.ClearToEmpty();
  _impl_.ip_address_.ClearToEmpty();
  ::memset(&_impl_.port_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.supports_mic_) -
      reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.supports_mic_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DiscoveryBeacon::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string app_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_app_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "com.audiostream.pb.DiscoveryBeacon.app_name"));
        } else
          goto handle_unusual;
        continue;
      // string server_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_server_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "com.audiostream.pb.DiscoveryBeacon.server_name"));
        } else
          goto handle_unusual;
        continue;
      // int32 port = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string version = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "com.audiostream.pb.DiscoveryBeacon.version"));
        } else
          goto handle_unusual;
        continue;
      // bool supports_opus = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.supports_opus_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool supports_mic = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.supports_mic_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string ip_address = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_ip_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "com.audiostream.pb.DiscoveryBeacon.ip_address"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DiscoveryBeacon::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.audiostream.pb.DiscoveryBeacon)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string app_name = 1;
  if (!this->_internal_app_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_app_name().data(), static_cast<int>(this->_internal_app_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.audiostream.pb.DiscoveryBeacon.app_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_app_name(), target);
  }

  // string server_name = 2;
  if (!this->_internal_server_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_server_name().data(), static_cast<int>(this->_internal_server_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.audiostream.pb.DiscoveryBeacon.server_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_server_name(), target);
  }

  // int32 port = 3;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_port(), target);
  }

  // string version = 4;
  if (!this->_internal_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_version().data(), static_cast<int>(this->_internal_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.audiostream.pb.DiscoveryBeacon.version");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_version(), target);
  }

  // bool supports_opus = 5;
  if (this->_internal_supports_opus() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_supports_opus(), target);
  }

  // bool supports_mic = 6;
  if (this->_internal_supports_mic() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_supports_mic(), target);
  }

  // string ip_address = 7;
  if (!this->_internal_ip_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip_address().data(), static_cast<int>(this->_internal_ip_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.audiostream.pb.DiscoveryBeacon.ip_address");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_ip_address(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.audiostream.pb.DiscoveryBeacon)
  return target;
}

size_t DiscoveryBeacon::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.audiostream.pb.DiscoveryBeacon)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string app_name = 1;
  if (!this->_internal_app_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_app_name());
  }

  // string server_name = 2;
  if (!this->_internal_server_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_server_name());
  }

  // string version = 4;
  if (!this->_internal_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_version());
  }

  // string ip_address = 7;
  if (!this->_internal_ip_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip_address());
  }

  // int32 port = 3;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_port());
  }

  // bool supports_opus = 5;
  if (this->_internal_supports_opus() != 0) {
    total_size += 1 + 1;
  }

  // bool supports_mic = 6;
  if (this->_internal_supports_mic() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DiscoveryBeacon::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DiscoveryBeacon::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DiscoveryBeacon::GetClassData() const { return &_class_data_; }


void DiscoveryBeacon::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DiscoveryBeacon*>(&to_msg);
  auto& from = static_cast<const DiscoveryBeacon&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.audiostream.pb.DiscoveryBeacon)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_app_name().empty()) {
    _this->_internal_set_app_name(from._internal_app_name());
  }
  if (!from._internal_server_name().empty()) {
    _this->_internal_set_server_name(from._internal_server_name());
  }
  if (!from._internal_version().empty()) {
    _this->_internal_set_version(from._internal_version());
  }
  if (!from._internal_ip_address().empty()) {
    _this->_internal_set_ip_address(from._internal_ip_address());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_supports_opus() != 0) {
    _this->_internal_set_supports_opus(from._internal_supports_opus());
  }
  if (from._internal_supports_mic() != 0) {
    _this->_internal_set_supports_mic(from._internal_supports_mic());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DiscoveryBeacon::CopyFrom(const DiscoveryBeacon& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.audiostream.pb.DiscoveryBeacon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiscoveryBeacon::IsInitialized() const {
  return true;
}

void DiscoveryBeacon::InternalSwap(DiscoveryBeacon* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.app_name_, lhs_arena,
      &other->_impl_.app_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.server_name_, lhs_arena,
      &other->_impl_.server_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.version_, lhs_arena,
      &other->_impl_.version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_address_, lhs_arena,
      &other->_impl_.ip_address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DiscoveryBeacon, _impl_.supports_mic_)
      + sizeof(DiscoveryBeacon::_impl_.supports_mic_)
      - PROTOBUF_FIELD_OFFSET(DiscoveryBeacon, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DiscoveryBeacon::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_audiostream_2eproto_getter, &descriptor_table_audiostream_2eproto_once,
      file_level_metadata_audiostream_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace audiostream
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::audiostream::pb::AudioFormat*
Arena::CreateMaybeMessage< ::com::audiostream::pb::AudioFormat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::audiostream::pb::AudioFormat >(arena);
}
template<> PROTOBUF_NOINLINE ::com::audiostream::pb::StreamConfig*
Arena::CreateMaybeMessage< ::com::audiostream::pb::StreamConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::audiostream::pb::StreamConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::com::audiostream::pb::MicControl*
Arena::CreateMaybeMessage< ::com::audiostream::pb::MicControl >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::audiostream::pb::MicControl >(arena);
}
template<> PROTOBUF_NOINLINE ::com::audiostream::pb::DiscoveryBeacon*
Arena::CreateMaybeMessage< ::com::audiostream::pb::DiscoveryBeacon >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::audiostream::pb::DiscoveryBeacon >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
