// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_client_2eproto;
namespace io {
namespace github {
namespace mkckr0 {
namespace audio_share_app {
namespace pb {
class AudioFormat;
struct AudioFormatDefaultTypeInternal;
extern AudioFormatDefaultTypeInternal _AudioFormat_default_instance_;
}  // namespace pb
}  // namespace audio_share_app
}  // namespace mkckr0
}  // namespace github
}  // namespace io
PROTOBUF_NAMESPACE_OPEN
template<> ::io::github::mkckr0::audio_share_app::pb::AudioFormat* Arena::CreateMaybeMessage<::io::github::mkckr0::audio_share_app::pb::AudioFormat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace io {
namespace github {
namespace mkckr0 {
namespace audio_share_app {
namespace pb {

// ===================================================================

class AudioFormat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:io.github.mkckr0.audio_share_app.pb.AudioFormat) */ {
 public:
  inline AudioFormat() : AudioFormat(nullptr) {}
  ~AudioFormat() override;
  explicit PROTOBUF_CONSTEXPR AudioFormat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AudioFormat(const AudioFormat& from);
  AudioFormat(AudioFormat&& from) noexcept
    : AudioFormat() {
    *this = ::std::move(from);
  }

  inline AudioFormat& operator=(const AudioFormat& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioFormat& operator=(AudioFormat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudioFormat& default_instance() {
    return *internal_default_instance();
  }
  static inline const AudioFormat* internal_default_instance() {
    return reinterpret_cast<const AudioFormat*>(
               &_AudioFormat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AudioFormat& a, AudioFormat& b) {
    a.Swap(&b);
  }
  inline void Swap(AudioFormat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudioFormat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AudioFormat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AudioFormat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AudioFormat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AudioFormat& from) {
    AudioFormat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AudioFormat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "io.github.mkckr0.audio_share_app.pb.AudioFormat";
  }
  protected:
  explicit AudioFormat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFormatTagFieldNumber = 1,
    kChannelsFieldNumber = 2,
    kSampleRateFieldNumber = 3,
    kBitsPerSampleFieldNumber = 4,
  };
  // int32 format_tag = 1;
  void clear_format_tag();
  int32_t format_tag() const;
  void set_format_tag(int32_t value);
  private:
  int32_t _internal_format_tag() const;
  void _internal_set_format_tag(int32_t value);
  public:

  // int32 channels = 2;
  void clear_channels();
  int32_t channels() const;
  void set_channels(int32_t value);
  private:
  int32_t _internal_channels() const;
  void _internal_set_channels(int32_t value);
  public:

  // int32 sample_rate = 3;
  void clear_sample_rate();
  int32_t sample_rate() const;
  void set_sample_rate(int32_t value);
  private:
  int32_t _internal_sample_rate() const;
  void _internal_set_sample_rate(int32_t value);
  public:

  // int32 bits_per_sample = 4;
  void clear_bits_per_sample();
  int32_t bits_per_sample() const;
  void set_bits_per_sample(int32_t value);
  private:
  int32_t _internal_bits_per_sample() const;
  void _internal_set_bits_per_sample(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:io.github.mkckr0.audio_share_app.pb.AudioFormat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t format_tag_;
    int32_t channels_;
    int32_t sample_rate_;
    int32_t bits_per_sample_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AudioFormat

// int32 format_tag = 1;
inline void AudioFormat::clear_format_tag() {
  _impl_.format_tag_ = 0;
}
inline int32_t AudioFormat::_internal_format_tag() const {
  return _impl_.format_tag_;
}
inline int32_t AudioFormat::format_tag() const {
  // @@protoc_insertion_point(field_get:io.github.mkckr0.audio_share_app.pb.AudioFormat.format_tag)
  return _internal_format_tag();
}
inline void AudioFormat::_internal_set_format_tag(int32_t value) {
  
  _impl_.format_tag_ = value;
}
inline void AudioFormat::set_format_tag(int32_t value) {
  _internal_set_format_tag(value);
  // @@protoc_insertion_point(field_set:io.github.mkckr0.audio_share_app.pb.AudioFormat.format_tag)
}

// int32 channels = 2;
inline void AudioFormat::clear_channels() {
  _impl_.channels_ = 0;
}
inline int32_t AudioFormat::_internal_channels() const {
  return _impl_.channels_;
}
inline int32_t AudioFormat::channels() const {
  // @@protoc_insertion_point(field_get:io.github.mkckr0.audio_share_app.pb.AudioFormat.channels)
  return _internal_channels();
}
inline void AudioFormat::_internal_set_channels(int32_t value) {
  
  _impl_.channels_ = value;
}
inline void AudioFormat::set_channels(int32_t value) {
  _internal_set_channels(value);
  // @@protoc_insertion_point(field_set:io.github.mkckr0.audio_share_app.pb.AudioFormat.channels)
}

// int32 sample_rate = 3;
inline void AudioFormat::clear_sample_rate() {
  _impl_.sample_rate_ = 0;
}
inline int32_t AudioFormat::_internal_sample_rate() const {
  return _impl_.sample_rate_;
}
inline int32_t AudioFormat::sample_rate() const {
  // @@protoc_insertion_point(field_get:io.github.mkckr0.audio_share_app.pb.AudioFormat.sample_rate)
  return _internal_sample_rate();
}
inline void AudioFormat::_internal_set_sample_rate(int32_t value) {
  
  _impl_.sample_rate_ = value;
}
inline void AudioFormat::set_sample_rate(int32_t value) {
  _internal_set_sample_rate(value);
  // @@protoc_insertion_point(field_set:io.github.mkckr0.audio_share_app.pb.AudioFormat.sample_rate)
}

// int32 bits_per_sample = 4;
inline void AudioFormat::clear_bits_per_sample() {
  _impl_.bits_per_sample_ = 0;
}
inline int32_t AudioFormat::_internal_bits_per_sample() const {
  return _impl_.bits_per_sample_;
}
inline int32_t AudioFormat::bits_per_sample() const {
  // @@protoc_insertion_point(field_get:io.github.mkckr0.audio_share_app.pb.AudioFormat.bits_per_sample)
  return _internal_bits_per_sample();
}
inline void AudioFormat::_internal_set_bits_per_sample(int32_t value) {
  
  _impl_.bits_per_sample_ = value;
}
inline void AudioFormat::set_bits_per_sample(int32_t value) {
  _internal_set_bits_per_sample(value);
  // @@protoc_insertion_point(field_set:io.github.mkckr0.audio_share_app.pb.AudioFormat.bits_per_sample)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace audio_share_app
}  // namespace mkckr0
}  // namespace github
}  // namespace io

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_2eproto
