name: Test

on:
  workflow_dispatch:

jobs:
  build_server_core:
    name: Build server-core
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            vcpkg_triplet: x64-windows-static-md
            cmake_preset: windows-Release
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux
            cmake_preset: linux-Release
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: server-core
    outputs:
      hash: ${{ steps.get_hash.outputs.hash }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Linux Deps
        run: sudo apt install libpipewire-0.3-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: e57b2167e66c847f991bd6bce1355b85acd944e8
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg_triplet }}
      - run: vcpkg integrate install
      - run: vcpkg install asio protobuf spdlog cxxopts
      - uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/server-core/CMakeLists.txt
          configurePreset: ${{ matrix.cmake_preset }}
          configurePresetAdditionalArgs: "['--target install']"
      - uses: actions/upload-artifact@v3
        with:
          name: server-core_${{ matrix.os }}
          path: out/install/${{ matrix.cmake_preset }}/bin/*
      - name: Get sha256num
        run: sha256sum out/install/${{ matrix.cmake_preset }}/bin/* | awk '{ printf "hash=%s", $1 }' | tee $GITHUB_OUTPUT
        id: get_hash
        shell: bash
