name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server-core
    steps:
    - uses: actions/checkout@v3
    
    # - uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: gradle
    # - name: create relese.jks
    #   run: mkdir ~/.android && echo "$release_jks" | base64 -d > ~/.android/release.jks
    #   env:
    #     release_jks: ${{ secrets.RELEASE_JKS }}
    # - name: create keystore.properties
    #   run: echo -e "storeFile=$(ls ~/.android/release.jks)\nstorePassword=${store_pass}\nkeyAlias=${key_alias}\nkeyPassword=${key_pass}\n" > keystore.properties
    #   env:
    #     store_pass: ${{ secrets.STORE_PASS }}
    #     key_alias: ${{ secrets.KEY_ALIAS }}
    #     key_pass: ${{ secrets.KEY_PASS }}
        
    # - run: chmod +x gradlew
    # - run: ./gradlew :app:signingReport
